export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    MARKETPLACE: '/marketplace',
    CATALOG: '/catalog',
    VENDORS: '/vendors',
    CART: '/cart',
    CHECKOUT: '/checkout',
    ORDERS: '/orders',
    WALLET: '/wallet',
    PAYMENTS: '/payments',
    MESSAGES: '/messages',
    NOTIFICATIONS: '/notifications',
    TRACKING: '/tracking',
    ABOUT: '/about',
    CONTACT: '/contact',
    FAQ: '/faq',
    HELP: '/help',
    TERMS: '/terms',
    PRIVACY: '/privacy',
    VENDOR: {
        DASHBOARD: '/vendor/dashboard',
        PRODUCTS: '/vendor/products',
        ADD_PRODUCT: '/vendor/products/add',
        EDIT_PRODUCT: (id) => `/vendor/products/edit/${id}`,
        STORE: '/vendor/store',
        ORDERS: '/vendor/orders',
    },
    ADMIN: {
        DASHBOARD: '/admin/dashboard',
        USERS: '/admin/users',
        PRODUCTS: '/admin/products',
        TRANSACTIONS: '/admin/transactions',
        CATEGORIES: '/admin/categories',
        RETURNS: '/admin/returns',
        ADS: '/admin/ads',
        DISPUTES: '/admin/disputes',
    },
    CARRIER: {
        DASHBOARD: '/carrier/dashboard',
    },
    BANK: {
        DASHBOARD: '/bank/dashboard',
    },
};
